= Goal of unit testing

WHAT IS AN ENTERPRISE APPLICATION?::
An enterprise application is an application that aims at automating or assisting an organization’s inner processes. It can take many forms, but usually the characteristics of an enterprise software are

* High business logic complexity
* Long lifespan
* Moderate amounts of data
* Low performance requirements

== Code design
Difficult to test = badly designed 
Easy to test != good design.

== Benefits
* Regression testing
** Not breaking old stuff
** Refactoring

* Ensure meeting requirements
** Can test edge cases easily

== Coverage
Measurement to see how much of code is covered by tests.

[source,clojure]
----
(fact "Is long string"
    (long-str? "abc") => false)

(defn long-str? [s]
    (> (count s) 5))
----


=== Test Coverage
100% coverage even though only one branch is tested.

=== Branch Coverage
50% coverage because only the less than 5 case is tested not the over 5 case.

[source,clojure]
----
(fact "Is long string"
    (long-str? "abc") => false)

(defn long-str? [s]
    (do (api/call)
        (> (count s) 5)))
----

=== Coverage with Side Effects
100% coverage however we are only testing output not side effects

== Successful test suite

* Target most important usecases
** Domain / Core layers
* Maximum value with minimum maintenance