= Goal of unit testing

WHAT IS AN ENTERPRISE APPLICATION?::
An enterprise application is an application that aims at automating or assisting an organization’s inner processes. It can take many forms, but usually the characteristics of an enterprise software are

* High business logic complexity
* Long lifespan
* Moderate amounts of data
* Low performance requirements

== Code design
If code is difficult to test then it's badly designed however it's not indicator that it is good design.

== Benefits
* Regression testing
** Not breaking old stuff
** Refactor 

== Coverage
Measurement to see how much of code is covered by tests.

[source,clojure]
----
(fact "Is long string"
    (long-str? "abc") => false)

(defn long-str? [s]
    (> (count s) 5))
----


=== Test Coverage
Executed lines / LOC.
Above test would be 100% coverage even though only one branch is tested.

=== Branch Coverage
Branches / number of branches.

Above test would be 50% coverage because only the less than 5 is tested on the over 5.

=== Coverage with Side Effects
This test would be 100% for both however we are only testing the string length logic not if the `api/call` works.

[source,clojure]
----
(fact "Is long string"
    (long-str? "abc") => false)

(defn long-str? [s]
    (do (api/call)
        (> (count s) 5)))
----

== Successful test suite

* Target most important usecases
** Domain / Core layers
* Maximum value with minimum maintenance