= What is a unit test

== Glossary

Classical (Black box, Bottom up)::
Testing the output.
Less brittle as not testing how only the output.
* (add 5 5) => 10 'Don't care how it works just as long as it gives me the correct results'

London (Mockist, Top down)::
Testing the implementation.
Test that internal implementation is called and stub output.
* Growing Object Oriented Software guided by Tests

Shared dependency::
Mutable state shared across tests.
If state changes then tests will become unpredictable because of race conditions. 

If first test swap's then then second fact runs it would fail.

[source,clojure]
----
(def state (atom ""))

(fact "abc is not a long string"
  (swap state "abc")
  (long-str? state) => false)

(fact "abcdefg is a long string"
  (swap state "abcdefg")
  (long-str? state) => true)

(defn long-str? [s]
  (> (count s) 5))
----

Unit test::
* Verifies small piece of code.
** Classical -> Unit of behaviour (function)
** London -> Object
* Quick
* Isolated
** Classical -> From other tests
** London -> Object

[source,clojure]
----
(fact "classical"
  (let [store (->Store)
        product "shampoo"
        _ (stock store product 10)
        customer (->Customer)
        _ (purchase customer store product 5)]
    (getInventory store product) => 5))

(fact "london"
  (let [product "shampoo"
        storeMock (reify IStore (in-stock? [product] true))
        _ (stock storeMock product 10)
        customer (->Customer)
        _ (purchase customer store product 5)]
    (called stockMock RemoveInventory) => 1))
----

== Isolation

Classical and London differ on Isolation.

* Classical -> Isolate the test
** Run tests in parallel
* London -> Isolate the implementation 
** Test covers specific component

== Naming

Describe tests for Domain expert or Business analyst.

NOTE: 'should be' is an anti-pattern use 'is'

* Good
** Delivery with a past date is invalid

* Bad
** DeliveryManager_Delivery_Invalid_Date