= Domain Driven Development Fundamentals

Tools to model the problem space (Domain)

Focus on behaviours/events of domain * Schedule appoint -> Appointment Scheduled * Book a room -> Room booked * Add item to calendar -> Item Added to calendar * Notify attendees -> Attendees notified

== Glossary

Domain (Problem space)::
A group of related items, topics, or subjects.

Domain Layer::
Modeling the Domain concepts and rules

Domain Service::
Orchestrator function for many objects. (stateless but can be side effectful)
* Process Order
* Send Message
* Transfer Between Accounts

Core domain::
Something that can't be outsourced

Domain Experts::
People who are experts within the domain/field/area

Sub Domain::
Smaller part of Domain

Bounded Context::
Independent system

Shared kernel::
Code reuse across bounded contexts (Logging)

Service (Orchestrator) ::
Stateless function which my have side effects

Ubiquitous language (Shared common language)::
** Explict about what you are talking about
** Use Domain terms instead of programming terms as it might be a lossy translation
** Avoids telephone game issue

Anemic domain model::
Just updates state (CRUD)

Rich domain model::
Implements many domain behaviours

Event::
Note of something that happened

Entity (Object)::
Something with an identity so that it can be tracked and persisted

Value Object::
Hash-map without identity.
(DateTimeRange - Has start and end time fields)

Aggregate::
Transactional graph of objects

Aggregate Root::
Api and maintains invariants for it's objects

Behaviour::
Some process

== Tips

* Explain your understanding back to Domain expert to identify gaps in knowledge

* Aggregate
** Acts as API to it's Objects
** Adds invariants so that it's objects can't be in an invalid state.
** Rules
*** Enforces invariants? All objects in a valid state
*** Saving change can save entire aggregate?
*** Deleting the aggregate also deletes all its objects? Is that okay?
** Group code by aggregate
