= Chapter 1
Kyle Grierson<griersonky@gmail.com>
1.0, January 13, 2022
:toc:

== What is a microservice

* Independently deployable services that are modeled around a business domain
** Encapsulates functionality and that are accessible to other services via a network
* Should have small external interfaces that rarely changes
** So implementation can change freely
** Consumers don't break
* Architecture
** Hexagonal/Ports and adapters/Onion/Clean
** Middle pure business logic
** Outside interfaces (APIS)

== Key concepts

* Independently deployable
** (Loosely coupled) Can release new/updated service without deploying other services
** Need explicit/strong/well-defined/stables contracts/interfaces between services to prevent breaking changes
* Modelled around a Business domain (DDD)
** Rolling out feature that requires changes to many services is costly
*** Need to coordinate the releases
* Prioritises high cohesion of business functionality over technical functionality
** Cohesion often refers to how the elements of a module belong together

* Don't share database
** If services share a database then they become coupled and changes need to coordinated between the two

* Size
** "Should be as big as your head" (What you find easily understood)
** As small an interface as possible

== Why

=== Composability

Business wants to reuse `user-profile` implementation for a different project

==== Mono

Reuse entire project just to use the user profile implementation

==== Micro

As services are small and focused they can be used in different business processes (Just tag users with new service label)

=== Scaling

`picture` feature of service is high in demand

==== Mono

Have to start up X more instances of your entire application just to support picture demand (Costly on cloud hosts)

==== Micro

Can scale different parts of your infrastructure À la carte.
Just start X more `picture services`

=== Smaller (Able to use new technology)

New (library/version of currently used library) comes out with new cool features that would be beneficial

==== Mono

Stuck with previous technology choices/versions, so you have to live with when adding new features or update entire system which may cause breaking changes

==== Micro

* Can leave old services on older tech and use newer services can use latest tech
* Services are small so can be easily rewritten/updated with new tech

=== Fault tolerant

System crashes because of new `picture` feature

==== Mono

Entire system down

==== Micro

Users can use rest of system just `picture` feature will be unavailable

== Essential tool

* Log aggregation tool
** Collect and aggregates logs from all services
** Humio, Datadog
* Trace
** Jaeger, Lightstep, Honeycomb

== Takeaways

* Pros
** Scaling, can spin up more instances for a particular service
** 1 service can fail but entire system keeps running
* Cons
** Managing loads of services
** Deploying loads of services
** Learn loads of new tools for managing microservices