= #1: Separate code and data

Benefits

* Code can be reused in different contexts
* Code can be tested in isolation
* Systems are less complex

== Code reused in different contexts

`Fullname` logic has to shared across both `Author` and `User` classes even though both have the same properties.
Inheritance could be used to share the implementation however if those classes needed to inherit from anything else then you need to create a new type hierarchy which combines the `Person` and the `NewParent` class.

[source,csharp]
----
    class Author
    {
        string Firstname { get; set; }
        string Lastname { get; set; }
        List<string> Books { get; set; }

        public Author(string firstname, string lastname, List<string> books)
        {
            Firstname = firstname;
            Lastname = lastname;
            Books = books;
        }
        public string Fullname()
        {
            return Firstname + " " + Lastname;
        }
    }

    class User
    {
        string Firstname { get; set; }
        string Lastname { get; set; }
        List<string> FavouriteAuthors { get; set; }

        public User(string firstname, string lastname, List<string> favouriteauthors)
        {
            Firstname = firstname;
            Lastname = lastname;
            FavouriteAuthors = favouriteauthors;
        }

        public string Fullname()
        {
            return Firstname + " " + Lastname;
        }
    }
----

However if we use duck typing the `fullname` function can handle any data as long as it has the right shape. 

[source,clojure]
----
(defrecord Author [firstname lastname books])
(defrecord User [firstname lastname FavouriteAuthors])

(defn fullname [{:keys [firstname lastname]}]
  (str firstname " " lastname))

(fullname (->Author "Lewis" "Carroll" ["Through the looking glass" "Jabberwocky"]))
(fullname (->User "Alice" "Wonderland" ["Lewis Carroll"]))
----

== Testing

When testing the `Fullname` method in OOP we have to instantiate a class which has additional dependencies (Author: books, User: FavouriteAuthors) however we only want to test the fullname function which only needs `firstname` and `lastname` so now we have to manage those additional dependences even though we aren't testing them.
Whereas with the dynamic functional approach we only need to know if the map has the keys `firstname` and `lastname` we don't care if it has more keys or not. 

Typed OOP approach

[source,csharp]
----
var sut = new Author("Alice", "Wonderland", List<string>(){"Extra dep we don't care about"});
sut.Fullname == "Alice Wonderland";
----

Dynamic Functional approach

[source,clojure]
----
(fullname {:firstname "Alice" :lastname "Wonderland"}) => "Alice Wonderland"
----

== Less complex

* Smaller scope for data and code entity
* Code and Data have less relations

== Cons

* No control on what code access what data
** Can't refactor shape of data as you don't know what functions expect that shape of data
* No packaging
** No IDE `dot` complete. Don't know what functions work your data.
** `Author` record could be in one file and `fullname` function could be in another and you have now way to know.
* More Code and Data
** But data is simpler has no dependency/context on the code